### ISSUE TITLE
try map

### ISSUE THREAD

**Issue by nmonhait** [nmonhait/westnile_epi#6]
@wendtke 

try the map now. upon learning about that warning, it is not a concern. it is simply saying we are overlaying different data onto the leaflet coordinates. i clear the environment and reran everything then printed the map titled "il" and it worked. let me know.

**Comment by wendtke** [comment]
@nmonhait 

When I print `il`, the layers are not combined; I see the full country map in the viewer tab, and the counties in the plot tab. What am I missing?

**Comment by nmonhait** [comment]
@wendtke 

I was able to fix the warning by changing the crs type as you will see in the code. the full map should show in the viewer.

**Comment by wendtke** [comment]
@nmonhait 
what is 'crs'? It still doesn't work

**Comment by wendtke** [comment]
@nmonhait 
the map still does not work

**Comment by nmonhait** [comment]
ive been trying to figure this out but will ask her first thing in class. sorry for the delay in progress!

**Comment by nmonhait** [comment]
@wendtke  ^^

**Comment by nmonhait** [comment]
@wendtke it may be easier to just collaborate on this tomorrow with both of our computers, but I tried my code in an Rmd and the correct map was able to output to all sources, so I seem to be getting somewhere. I pushed that Rmd in case you wanted to try on your end. Otherwise, I can show you all of this tomorrow.

**Comment by wendtke** [comment]
it still isn't working on my computer. let's try to make some progress tomorrow.

**Comment by nmonhait** [comment]
@wendtke 

28 |   | #add latitude and longitude to original dataset
-- | -- | --
29 |   |  
30 |   | library(readr)
31 |   | data_il <- read_csv("data/data_il.csv") %>%
32 |   | rename(NAME = il)
33 |   |  
34 |   | il_counties_2 <- il_counties %>%
35 |   | select(STATEFP, COUNTYFP, geometry, NAME)
36 |   |  
37 |   | full_il <- inner_join(data_il, il_counties, by = "NAME")

**Comment by jessyjj** [comment]
i just run on my computer, the same issue happened to me too. I could see the map but it is not zoomed in to il
